version: '3.4'

services:
  codespacesreact:
    image: codespacesreact
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
